### PR TITLE
Create TailgateBehaviour.xml

### PR DESCRIPTION
**Pull request by Perry-Gunn**
Control unlocking/opening of tailgate from fob on F25 X3 (may work on others),

### CODE REVIEW

**Comment by packetpilot** [comment]
This doesn't follow naming conventions for the file. File should be named after the author.

**Comment by Perry-Gunn** [comment]
Apologies - file renamed

**Comment by Perry-Gunn** [comment]
Hi Dave,

 

I don’t know if I did something wrong but after I renamed the file and you merged it, is showed for a while but has now disappeared

 

After you merged it, I received an email saying that the fork/branch could be deleted, so I did so – would that have caused it to disappear from your ‘master’? If so I have restored the branch

 

Apologies – I have never used github before so I have a bit of a learning curve…

 

Cheers

 

Perry

**Comment by packetpilot** [comment]
It appears after checking the commit history that @botho would have to comment here, as it looks like your file disappeared in one of his [commits-and-merges](https://github.com/packetpilot/bmw-f/commit/0d06a4e87557fbaa95f373b4fdd26ca23dd3cb6c).

**Comment by Perry-Gunn** [comment]
OK – Almaretto checked the xml file for me before I submitted it so I’m pretty sure it was OK – what do I do? Contact @botho?

 

Sorry, as I said, github is a bit new to me…

**Comment by packetpilot** [comment]
He should see his mentions here but a comment on that specific commit (which you've now made) is the right move.

**Comment by Perry-Gunn** [comment]
Thanks, I'll just wait ans see what he says then...

**Pull request merged**
