### PR TITLE
Proposed changes to include G07 coding

### PR DESCRIPTION
**Pull request by jokinawa**
Thank you.

### CODE REVIEW

**Comment by botho** [comment]
merged.
To update this directly in Launcher, you need to add it by yourself the first time in both directories :

C:\Program Files (x86)\TokenMaster\LauncherPRO\FDLCodes (default files : never updated)
C:\ProgramData\TokenMaster\Launcher PRO\FDLCodes (files updated by launcher when you commit new stuff here into the Git repo)

**Comment by bmwdriva** [comment]
New Launcher PRO_3.4.0.191 Esys 3.33.4
https://mega.nz/#F!Vzw23YrI!Vdv9Yizl1ahygmebZWuCdQ
Completely ready installation for work with F/G/I/R-series.
instant activation.

**Comment by bmwdriva** [comment]
MGU:
6C3: No changes in MGU

6CP:
HU_MGU_01 > CONNECTIVITY_A4A 3001 > WLAN_WIFI_MODE = ap+go
HU_MGU_01 > SYSTEM_CONFIGURATION 3004 > CARPLAY_SWT = aktiv
HU_MGU_01 > TELEMATICS 3003 > WLAN_DIAGNOSE = aktiv

6CP + 6NR:
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_ANDROID = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_PIA = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_REMOTE_APPS = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_STT_SPELLER_INPUT = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_SWT = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_WIRELESS_ANDROID = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_WIRELESS_IOS = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > REMOTE_HMI = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > WLAN_WIFI_MODE = ap+go
HU_MGU_01 > SYSTEM_CONFIGURATION 3004 > CARPLAY_SWT = aktiv
HU_MGU_01 > TELEMATICS 3003 > WLAN_DIAGNOSE = aktiv

6CP + 6NR + 6AP + 6AE:
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_ANDROID = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_PIA = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_REMOTE_APPS = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_STT_SPELLER_INPUT = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_SWT = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_WIRELESS_ANDROID = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > A4A_WIRELESS_IOS = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > REMOTE_HMI = aktiv
HU_MGU_01 > CONNECTIVITY_A4A 3001 > WLAN_WIFI_MODE = ap+go
HU_MGU_01 > NAVIGATION 3006 > SYSTEM_GPS_RECEIVER = nicht_aktiv
HU_MGU_01 > NAVIGATION 3006 > TI_ONLINE = aktiv
HU_MGU_01 > TELEMATICS 3003 > CONTACT_PICTURE_ONLINE_DOWNLOAD = aktiv
HU_MGU_01 > TELEMATICS 3003 > CONTACTS_FROM_ONLINE_SOURCE = aktiv
HU_MGU_01 > TELEMATICS 3003 > IPCE_WEBSERVER = aktiv
HU_MGU_01 > TELEMATICS 3003 > ONLINE_SERVICES = aktiv
HU_MGU_01 > TELEMATICS 3003 > ONLINE_SERVICES_GLS = aktiv
HU_MGU_01 > TELEMATICS 3003 > TELEMATIC_ECU = atm_2
HU_MGU_01 > TELEMATICS 3003 > WLAN_DIAGNOSE = aktiv

**Comment by CuchoM** [comment]
> New Launcher PRO_3.7 Esys 3.34.0
> 
> https://mega.nz/#F!Vzw23YrI!Vdv9Yizl1ahygmebZWuCdQ
> 
> Completely ready installation for work with F/G/I/R-series.
> 
> instant activation.

Could you please share again the files ? the link is broken .

**Pull request merged**
