### PR TITLE
EuroMDM 59.0

### PR DESCRIPTION
**Pull request by aboulfad**
Updated UiwSetLevelPc to 0x11 as per psdZ 59.0.

### CODE REVIEW

**Comment by aboulfad** [comment]
Dave, do not merge :)

**Comment by thisisdave** [comment]
Not merging, just saw this hanging around. Glad to sit on my hands. :-)

**Comment by aboulfad** [comment]
Hahaha,no merge needed and may leave this branch hanging as it is appearing like EuroMDM is just one parameter... (From the latest discussions)

**Comment by aboulfad** [comment]
I've created another branch and merged it to main with latest setting. Leave this as an orphan.

**Pull request closed without merging**
