### PR TITLE
- comment

### PR DESCRIPTION
**Pull request by botho**

### CODE REVIEW

**Comment by botho** [comment]
Thanks Dave for all your merges 👍 
Do you know why I have error when updating XML in the Launcher ? Can't find any logs file and didn't find any problem in my FDL file

**Comment by packetpilot** [comment]
No problem--I can add you as a maintainer to the project since you're certainly the most active! LMK if you'd prefer that.

I don't actually have any insight into the repo's integration with the launcher (neither premium nor pro, although the latter is what I use). I can say that the only time I've had issues updating is when my coding VM didn't have a network connection to my host. TM or shawnsheridan may have more insight into the actual integration into the launcher in case you do have an issue beyond the VM's ability to talk to the internet.

**Comment by danieltutuianu** [comment]
I noticed that the file that I added "tutuianu_daniel.xml" is not present after you install Launcher ( Pro or Premium ) even if is in master branch. Do you know why ?

**Comment by botho** [comment]
@danieltutuianu,
You need to copy your XML into C:\Program Files (x86)\TokenMaster\E-Sys Launcher PRO\FDLCodes to be able to see you file into the Launcher.
Then when you push an update into this repo, the launcher will download it into C:\ProgramData\TokenMaster\E-Sys Launcher PRO\FDLCodes

**Comment by botho** [comment]
@packetpilot,
Thanks for invitation (accepted 👍 )
I just read that ... I will have a test 

TokenMaster's Launcher V2.7.1 Premium and PRO are now out.

Change log

Launcher PRO V2.7.1 Build 148
====================
**- Fixed "Unknown Error" when retrieving cheat codes**
- Improved Launcher-E-Sys communication
- Reduced memory usage
- "Code Default Values" button renamed to "DO NOT USE!!!" ("VERWENDEN SIE KEINE!!!")
- Minor bug fix

**Comment by danieltutuianu** [comment]
@packetpilot I have the xml into FDLCodes and I'm able to see the file into the Launcher. The thing  is when you install Launcher you don't get this file as the other files. I should do another push ?

**Comment by botho** [comment]
@danieltutuianu,

You need to send your XML to Tokenmaster and I'll do integration of it into his next Launcher release ...

**Comment by danieltutuianu** [comment]
alright. I didn't know.

**Comment by botho** [comment]
Solved my problem ( DO NOT WRITE "<" in comment)

**Pull request merged**
