### PR TITLE
Add Cheat Sheet

### PR DESCRIPTION
**Pull request by alexpeterson91**
Added initial personal cheat sheet, primarily F025 codes

### CODE REVIEW

**Comment by packetpilot** [comment]
Any chance you could convert to markdown? Perhaps there's a converter. I'm all for inclusion of cheat sheets, but if not in a full-blown wiki, I think markdown would maximize accessibility.

**Comment by alexpeterson91** [comment]
To be honest I’m not sure how to convert it to markdown, I’ve been working with Almaretto to get the xml formatting correct, and just got it to display correctly.

Im googling around for a converter but so far its just confusing me more, but ill keep at it.

**Comment by Almaretto** [comment]
I am confused. What is a markdown?

Besides the unnecessary, redundant entries, it seems to be formatted correctly.

**Comment by packetpilot** [comment]
https://en.m.wikipedia.org/wiki/Markdown

**Comment by packetpilot** [comment]
Wow, my apologies. Without actually checking actual file content, I assumed this was a cheat sheet that was a spreadsheet, not a cheat code file (as I've only ever seen cheat sheets refer to table-based documents as opposed to cheat code xml files).

That said, it'd be best for duplicates to be removed. Would you mind doing that?

I've been (and will continue to be) pretty heads-down at #newjob so my apologies for not being thorough.

**Pull request closed without merging**
